version: '3.6'
services:
  postgres:
    build: services/postgre
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=password

  myapp:
    build: services/myapp
    ports:
      - "8085:8080"
    depends_on:
      - postgres

#docker-compose up --build